[tools]
golangci-lint = "2.5.0"
"vfox-pulumi:pulumi/pulumi-converter-terraform" = "latest"
"vfox-pulumi:pulumi/pulumi-aws" = "latest"
"vfox-pulumi:pulumi/pulumi-vault" = "latest"
"vfox-pulumi:pulumi/pulumi-random" = "latest"
"vfox-pulumi:pulumi/pulumi-std" = "latest"